version: "1"

context:

  active-host: "ln109.us1.dbt.com"

  active-project: "70471823422016"

projects:

  - project-name: "Analytics"

    project-id: "70471823422016"

    account-name: "Siepomaga "

    account-id: "70471823419066"

    account-host: "ln109.us1.dbt.com"

    token-name: "cloud-cli-9836"

    token-value: "dbtu_FO5kPHM27evNuuNvciYUYvE8KyXnbh4YMEsHk99EZRkEpfaxrs"


    
    
