name: 'Analytics'
version: '1.0'
config-version: 2

profile: 'profil_projektu'

# Opcjonalne ustawienia
target-path: "target/"
clean-targets:
  - "target"
  - "dbt_modules"
version: "1"
context:
  active-host: "nl214.us1.dbt.com"
  active-project: "70471823418738"
projects:
  - project-name: "Analytics"
    project-id: "70471823418738"
    account-name: "Pomoc "
    account-id: "70471823416086"
    account-host: "nl214.us1.dbt.com"
    
    
