name: 'Analytics'
version: '1.0'
config-version: 2

profile: 'siepomaga-645d1'

# Opcjonalne ustawienia
target-path: "target/"
clean-targets:
  - "target"
  - "dbt_modules"
version: "1"
context:
  active-host: "ln109.us1.dbt.com"
  active-project: "70471823419066"
projects:
  - project-name: "Analytics"
    project-id: "70471823419066"
    account-name: "siepomaga-645d1"
    account-id: "70471823419066"
    account-host: "ln109.us1.dbt.com"
    
    
